onlyBuiltDependencies:
  - esbuild

overrides:
  axios: ^1.20.0
  esbuild: ^0.28.2
  dompurify: ^3.4.14
  js-yaml: 5.4.1
  linkify-it: ^5.0.2
  markdown-it: ^14.3.1
  mermaid: ^11.17.2
  undici: ^8.10.1
  vite@^7.0.0: ^8.2.2
  vitepress>vite: ^8.2.2
